#' Create a yaml metadata file
#'
#' This function is used to create a yaml metadata file when executing
#' a data pipeline that describes the data pipeline and the data queried
#' through the data pipeline.
#'
#' @param pipeline_id individual id of data pipeline
#' @param pipeline_creators creators of the data pipeline, see \link{people}
#' @param pipeline_date date YYYY-MM-DD (%Y-%m-%s) that pipeline was created
#' @param pipeline_url url to data pipeline code
#' @param data_pipeline_uuid uuid of the data associated with the pipeline. If no bbox or temporal constraits are used for the query, this uuid should always be the same. If a temporal range of a bounding box are imposed, this means that the resulting data are different from the original and thus a new uuid should be used.
#' @param data_pipeline_bbox bounding box that was used to spatially subset the queried data, if applicable. The bounding box should be of the form c(xmin, ymin, xmax, ymax),
#' @param data_pipeline_timespan time span that was used to temporally subset the queried data, if applicable. The time span should a vector containing all the years to be queried c(year1, year2, ...),
#' @param data_name short name of data queried
#' @param data_description description of data queried
#' @param data_access access date of queried data
#' @param data_temporal temporal coverage of data, if applicable
#' @param data_bbox bounding box of data of the form c(xmin, ymin, xmax, ymax), if applicable
#' @param data_contacts contacts for data queried, see \link{people}
#' @param data_url data url, if applicable
#' @param data_uuid data uuid, e.g. from API or open data portals, if applicable
#' @param data_availability availability of queried data, one of c('open','on demand','data sharing agreement','restricted')
#' @param data_citekey vector of citation keys for reference to bibtex files
#' @param first_name first name
#' @param last_name last name
#' @param email email address
#' @param affiliation affiliation
#' @param role role
#' @param developer predetermined "people", currently "david", "vincent"
#' @param meta meta list generated by `metadata()` and used as first argument of `add_metadata()`
#' @param ... further arguments used in `add_template()` to include additional metadata information on the queried data.
#'
#' @return This function returns a yaml metadata
#'
#' @export
#'
#' @examples
#' \dontrun{
#' meta <- metadata(
#'   pipeline_id = "jhag76ad",
#'   pipeline_creators = people(developer = "david"),
#'   pipeline_date = "2022-04-13",
#'   pipeline_url = "https://path/to/pipeline.R",
#'   data_pipeline_uuid = "kjashf-aksjfg-soa8f7g-so8ef7",
#'   data_pipeline_bbox = c(xmin = -55, ymin = -55, xmax = -50, ymax = -50)
#'   data_pipeline_timespan = 2022,
#'   data_name = "Data X",
#'   data_description = "Data X characterizes Y",
#'   data_access = "2022-06-25",
#'   data_temporal = c(2000:2002, 2022),
#'   data_bbox = c(xmin = -60, ymin = -60, xmax = -40, ymax = -40),
#'   data_contacts = people("Jojo", "Le rigolo", "jojo@coolmain.com", "DFO", "Assistant"),
#'   data_url = "https://path/to/data/",
#'   data_uuid = "akiuy1-skjhfgkj-jhkasvf-mahsvbf",
#'   data_availability = "open",
#'   data_citekey = c("lerigolo2022", "archambault1990")
#' )
#'
#' meta <- add_metadata(meta,
#'   species = c("Cod", "Capelin", "Shrimp"),
#'   gear = c("Trawl", "Longline")
#' )
#' }
#' @export
#' @describeIn metadata export metadata yaml
metadata <- function(pipeline_id, pipeline_creators, pipeline_date, pipeline_url, data_name,  data_pipeline_uuid, data_pipeline_bbox = NULL, data_pipeline_timespan = NULL, data_description, data_access = timestamp(), data_temporal = NULL, data_bbox = NULL, data_contacts, data_url = NULL, data_uuid = NULL, data_availability = NULL, data_citekey) {

  # Metadata list
  meta <- list()

  # Pipeline metadata
  meta$pipeline <- list()
  meta$pipeline$pipeline_id <- pipeline_id
  meta$pipeline$creators <- dplyr::bind_rows(pipeline_creators)
  meta$pipeline$date_created <- pipeline_date
  meta$pipeline$url <- pipeline_url

  # Data medata
  meta$data <- list()
  meta$data$data_pipeline <- list()
  meta$data$data_pipeline$data_pipeline_uuid <- data_pipeline_uuid
  meta$data$data_pipeline$data_pipeline_bbox <- data_pipeline_bbox
  meta$data$data_pipeline$data_pipeline_timespan <- data_pipeline_timespan
  meta$data$name <- data_name
  meta$data$description <- data_description
  meta$data$access_date <- data_access
  meta$data$temporal <- data_temporal
  meta$data$bbox <- data_bbox
  meta$data$contacts <- dplyr::bind_rows(data_contacts)
  meta$data$url <- data_url
  meta$data$uuid <- data_uuid
  meta$data$availability <- data_availability
  meta$data$citekey <- data_citekey

  # Return
  invisible(meta)
}

#' @describeIn metadata add additional information on queried data to metadata
#' @export
add_metadata <- function(meta, ...) {
  invisible(
    c(meta, list(...))
  )
}

#' @describeIn metadata add pipeline creators and data contacts
#' @export
people <- function(first_name = NULL, last_name = NULL, email = NULL, affiliation = NULL, role = NULL, developer = NULL) {
  if (!is.null(developer)) {
    if (developer == "david") {
      c(
        first_name = "David",
        last_name = "Beauchesne",
        email = "david.beauchesne@hotmail.com",
        affiliation = "Université Laval",
        role = "Postdoctoral researcher"
      )
    } else if (developer == "vincent") {
      c(
        first_name = "Vincent",
        last_name = "Bellavance",
        email = "Vincent.Bellavance@USherbrooke.ca",
        affiliation = "Université Laval",
        role = "Research professional / data scientist"
      )
    } else {
      message("This developer is unknown to us...")
    }
  } else {
    c(
      first_name = first_name,
      last_name = last_name,
      email = email,
      affiliation = affiliation,
      role = role
    )
  }
}
