#' Create a yaml metadata file
#'
#' This function is used to create a yaml metadata file when executing
#' a data pipeline that describes the data pipeline and the data queried
#' through the data pipeline.
#'
#' @param pipeline_type type of pipeline, one of "data" or "integration"
#' @param pipeline_id individual id of data pipeline
#' @param pipeline_creators creators of the data pipeline
#' @param pipeline_date date YYYY-MM-DD (%Y-%m-%s) that pipeline was created
#' @param pipeline_url url to data pipeline code
#' @param pipeline_bbox bounding box that was used to spatially subset the queried data, if applicable. The bounding box should be of the form c(xmin, ymin, xmax, ymax),
#' @param pipeline_timespan time span that was used to temporally subset the queried data, if applicable. The time span should a vector containing all the years to be queried c(year1, year2, ...),
#' @param name short name of data queried
#' @param description description of data queried
#' @param access access date of queried data
#' @param contacts contacts for data queried
#' @param citekey vector of citation keys for reference to bibtex files
#' @param data_timespan temporal coverage of data, if applicable
#' @param data_bbox bounding box of data of the form c(xmin, ymin, xmax, ymax), if applicable
#' @param data_url data url, if applicable
#' @param data_uuid data uuid, e.g. from API or open data portals, if applicable
#' @param data_availability availability of queried data, one of c('open','on demand','data sharing agreement','restricted')
#' @param integration_data unique identifier of raw data pipelines used for the integration pipeline
#' @param integration_grid details of the grid used for data integration
#' @param meta meta list generated by `metadata()` and used as first argument of `add_metadata()`
#' @param grd object containing grid
#' @param ... further arguments used in `add_template()` to include additional metadata information on the queried data.
#'
#' @return This function returns a yaml metadata
#'
#' @export
#'
#' @examples
#' \dontrun{
#' meta <- get_metadata(
#'   pipeline_id = uid,
#'   pipeline_bbox = bbox,
#'   pipeline_timespan = timespan,
#'   access = timestamp(),
#'   data_bbox = sf::st_bbox(dat),
#' )
#'
#' meta <- add_metadata(meta,
#'   species = c("Cod", "Capelin", "Shrimp"),
#'   gear = c("Trawl", "Longline")
#' )
#' }
#' @export
#' @describeIn metadata export metadata yaml
metadata <- function(pipeline_type,
                     pipeline_id,
                     pipeline_creators,
                     pipeline_date,
                     pipeline_url,
                     pipeline_bbox = NULL,
                     pipeline_timespan = NULL,
                     name,
                     description,
                     contacts = NULL,
                     access = timestamp(),
                     citekey,
                     data_timespan = NULL,
                     data_bbox = NULL,
                     data_url = NULL,
                     data_uuid = NULL,
                     data_availability = NULL,
                     integration_data = NULL,
                     integration_grid = NULL) {

  # Metadata list
  meta <- list()

  # Pipeline metadata
  meta$pipeline <- list()
  meta$pipeline$pipeline_id <- pipeline_id
  meta$pipeline$pipeline_type <- pipeline_type
  meta$pipeline$creators <- pipeline_creators
  meta$pipeline$date_created <- pipeline_date
  meta$pipeline$url <- pipeline_url
  meta$pipeline$pipeline_bbox <- pipeline_bbox
  meta$pipeline$pipeline_timespan <- pipeline_timespan

  # Description of data or integration pipeline
  meta$description <- list()
  meta$description$name <- name
  meta$description$description <- description
  meta$description$access_date <- access
  meta$description$contacts <- contacts
  meta$description$citekey <- citekey

  if (pipeline_type == "data") {
    meta$description$timespan <- data_timespan
    meta$description$bbox <- data_bbox
    meta$description$url <- data_url
    meta$description$uuid <- data_uuid
    meta$description$availability <- data_availability
  }

  if (pipeline_type == "integration") {
    meta$description$integration_data <- integration_data
    meta$description$grid <- integration_grid
  }

  # Return
  invisible(meta)
}

#' @describeIn metadata builds metadata from internal package data
#' @export
get_metadata <- function(pipeline_type, pipeline_id, pipeline_bbox = NULL, pipeline_timespan = NULL, access = timestamp(), data_bbox = NULL, data_timespan = NULL, integration_grid = NULL, ...) {
  dat <- get_pipeline(pipeline_id)
  contact <- get_contact(pipeline_id)
  if (nrow(contact) == 0) contact <- NULL
  meta <- metadata(
    pipeline_id = pipeline_id,
    pipeline_type = pipeline_type,
    pipeline_creators = get_creator(pipeline_id),
    pipeline_date = dat$date_created,
    pipeline_url = get_pipeline_url(pipeline_id),
    pipeline_bbox = pipeline_bbox,
    pipeline_timespan = pipeline_timespan,
    name = get_name(pipeline_id),
    description = get_description(pipeline_id),
    access = access,
    contacts = contact,
    citekey = get_citekey(pipeline_id),
    data_timespan = data_timespan,
    data_bbox = data_bbox,
    data_url = dat$data_url,
    data_uuid = dat$data_uuid,
    data_availability = dat$data_availability,
    integration_data = get_rawid(pipeline_id),
    integration_grid = integration_grid
  )
}

#' @describeIn metadata add additional information on queried data to metadata
#' @export
add_metadata <- function(meta, ...) {
  invisible(
    c(meta, list(...))
  )
}


#' @describeIn metadata add additional information on queried data to metadata
#' @export
add_metadata <- function(meta, ...) {
  invisible(
    c(meta, list(...))
  )
}


#' @describeIn metadata Script to extract metadata and contact from raw data list
#' @export
gather_meta <- function() {
  # List of raw data 
  files <- dir(
    here::here("data","pipedat"),
    recursive = TRUE,
    full.names = TRUE,
    pattern = ".yaml$"
  )

  # Import them all 
  dat <- lapply(
    files, 
    yaml::read_yaml
  ) 
  
  # Build table of raw data and contacts for the project
  meta <- contact <- list()
  for(i in 1:length(dat)) {
    d <- dat[[i]]
    
    # -----
    timespan <- suppressWarnings(range(d$description$timespan, na.rm = TRUE))
    timestart <- timespan[1]
    timestop <- timespan[2]
    if (timespan[1] == Inf) {
      timespan <- "-"
    } else {
      timespan <- ifelse(
        timestart == timestop, 
        timestart, 
        glue::glue("{timestart}-{timestop}")
      )
    }
    timespan <- as.character(timespan)
    
    # -----
    contact[[i]] <- suppressWarnings(dplyr::bind_rows(d$description$contacts))
    
    # -----
    meta[[i]] <- data.frame(
      uid = d$pipeline$pipeline_id,
      uid_url = d$pipeline$url,
      name = d$description$name,
      description = d$description$description,
      access = d$description$access_date,
      contact = paste0(contact[[i]]$contact_id, collapse = ","),
      source = paste0(glue::glue("@{d$description$citekey}"), collapse = "; "),
      timespan = timespan,
      url = d$description$url
    )
  }
  
  meta <- dplyr::bind_rows(meta)
  contact <- dplyr::bind_rows(contact) |>
             dplyr::select(contact_id, first_name, last_name, organization, email) |>
             dplyr::distinct() |>
             dplyr::arrange(contact_id)
  
  # Export
  out <- here::here("data","pipedat")
  write.csv(meta, here::here(out, "metadata.csv"), row.names = FALSE)
  write.csv(contact, here::here(out, "contacts.csv"), row.names = FALSE)
}

#' @describeIn metadata Script to create a single bib file from the downloaded raw data using pipedat
#' @export
gather_bib <- function() {
  # List of bib files 
  files <- dir(
    here::here("data","pipedat"),
    recursive = TRUE,
    full.names = TRUE,
    pattern = ".bib$"
  )
  
  # Remove pipedat.bib from list if it already exists 
  uid <- stringr::str_detect(files, "pipedat.bib")
  files <- files[!uid]
  
  # Import them all 
  dat <- lapply(
    files, 
    RefManageR::ReadBib
  ) 
  dat <- do.call("c", dat) |>
    RefManageR::WriteBib(
    file = here::here("data","pipedat","pipedat.bib"), 
    verbose = FALSE
  )
}

