#' Create a yaml metadata file
#'
#' This function is used to create a yaml metadata file when executing
#' a data pipeline that describes the data pipeline and the data queried
#' through the data pipeline.
#'
#' @param pipeline_id individual id of data pipeline
#' @param pipeline_creators creators of the data pipeline
#' @param pipeline_date date YYYY-MM-DD (%Y-%m-%s) that pipeline was created
#' @param pipeline_url url to data pipeline code
#' @param pipeline_crs spatial projection used to transform the spatial data into a uniform projection. Default is set to `crs = 4326`
#' @param pipeline_bbox bounding box that was used to spatially subset the queried data, if applicable. The bounding box should be of the form c(xmin, ymin, xmax, ymax),
#' @param pipeline_timespan time span that was used to temporally subset the queried data, if applicable. The time span should a vector containing all the years to be queried c(year1, year2, ...),
#' @param data_name short name of data queried
#' @param data_description description of data queried
#' @param data_access access date of queried data
#' @param data_timespan temporal coverage of data, if applicable
#' @param data_bbox bounding box of data of the form c(xmin, ymin, xmax, ymax), if applicable
#' @param data_contacts contacts for data queried
#' @param data_url data url, if applicable
#' @param data_uuid data uuid, e.g. from API or open data portals, if applicable
#' @param data_availability availability of queried data, one of c('open','on demand','data sharing agreement','restricted')
#' @param data_citekey vector of citation keys for reference to bibtex files
#' @param meta meta list generated by `metadata()` and used as first argument of `add_metadata()`
#' @param ... further arguments used in `add_template()` to include additional metadata information on the queried data.
#'
#' @return This function returns a yaml metadata
#'
#' @export
#'
#' @examples
#' \dontrun{
#' meta <- get_metadata(
#'   pipeline_id = uid,
#'   pipeline_crs = crs,
#'   pipeline_bbox = bbox,
#'   pipeline_timespan = timespan,
#'   data_access = timestamp(),
#'   data_bbox = sf::st_bbox(dat),
#' )
#'
#' meta <- add_metadata(meta,
#'   species = c("Cod", "Capelin", "Shrimp"),
#'   gear = c("Trawl", "Longline")
#' )
#' }
#' @export
#' @describeIn metadata export metadata yaml
metadata <- function(pipeline_id, pipeline_creators, pipeline_date, pipeline_url, pipeline_crs, pipeline_bbox = NULL, pipeline_timespan = NULL, data_name, data_description, data_access = timestamp(), data_timespan = NULL, data_bbox = NULL, data_contacts, data_url = NULL, data_uuid = NULL, data_availability = NULL, data_citekey) {

  # Metadata list
  meta <- list()

  # Pipeline metadata
  meta$pipeline <- list()
  meta$pipeline$pipeline_id <- pipeline_id
  meta$pipeline$creators <- pipeline_creators
  meta$pipeline$date_created <- pipeline_date
  meta$pipeline$url <- pipeline_url
  meta$pipeline$pipeline_crs <- pipeline_crs
  meta$pipeline$pipeline_bbox <- pipeline_bbox
  meta$pipeline$pipeline_timespan <- pipeline_timespan

  # Data medata
  meta$data <- list()
  meta$data$name <- data_name
  meta$data$description <- data_description
  meta$data$access_date <- data_access
  meta$data$timespan <- data_timespan
  meta$data$bbox <- data_bbox
  meta$data$contacts <- data_contacts
  meta$data$url <- data_url
  meta$data$uuid <- data_uuid
  meta$data$availability <- data_availability
  meta$data$citekey <- data_citekey

  # Return
  invisible(meta)
}

#' @describeIn metadata builds metadata from internal package data
#' @export
get_metadata <- function(pipeline_id, pipeline_crs = 4326, pipeline_bbox = NULL, pipeline_timespan = NULL, data_access = timestamp(), data_bbox = NULL, data_timespan = NULL, ...) {
  dat <- get_pipeline(pipeline_id)
  meta <- metadata(
    pipeline_id = pipeline_id,
    pipeline_creators = get_creator(pipeline_id),
    pipeline_date = dat$date_created,
    pipeline_url = get_pipeline_url(pipeline_id),
    pipeline_crs = pipeline_crs,
    pipeline_bbox = pipeline_bbox,
    pipeline_timespan = pipeline_timespan,
    data_name = get_name(pipeline_id),
    data_description = get_description(pipeline_id),
    data_access = data_access,
    data_timespan = data_timespan,
    data_bbox = data_bbox,
    data_contacts = get_contact(pipeline_id),
    data_url = dat$data_url,
    data_uuid = dat$data_uuid,
    data_availability = dat$data_availability,
    data_citekey = get_citekey(pipeline_id)
  )
}

#' @describeIn metadata add additional information on queried data to metadata
#' @export
add_metadata <- function(meta, ...) {
  invisible(
    c(meta, list(...))
  )
}


# ------------------------------------------------------------
# Metadata helper functions
get_pipeline <- function(pipeline_id) {
  dat <- pipeline
  uid <- dat$pipeline_id %in% pipeline_id
  dat[uid, ]
}

get_shortname <- function(pipeline_id) {
  dat <- get_pipeline(pipeline_id)
  dat$data_shortname
}

get_name <- function(pipeline_id) {
  dat <- get_pipeline(pipeline_id)
  dat$data_name
}

get_description <- function(pipeline_id) {
  dat <- get_pipeline(pipeline_id)
  dat$data_description
}

get_contact <- function(pipeline_id) {
  dat <- pcontact
  uid <- dat$pipeline_id %in% pipeline_id
  iid <- dat$contact_id[uid]
  contact[contact$contact_id %in% iid, ]
}

get_creator <- function(pipeline_id) {
  dat <- pcreator
  uid <- dat$pipeline_id %in% pipeline_id
  iid <- dat$contact_id[uid]
  contact[contact$contact_id %in% iid, ]
}

get_citekey <- function(pipeline_id) {
  dat <- pcite
  uid <- dat$pipeline_id %in% pipeline_id
  dat$citekey[uid]
}

get_bib <- function(pipeline_id) {
  iid <- get_citekey(pipeline_id)
  bib[[bib$key %in% iid]]
}

get_pipeline_url <- function(pipeline_id) {
  dat <- get_pipeline(pipeline_id)
  repo <- "https://github.com/Ecosystem-Assessments/pipedat"
  glue("{repo}/blob/main/R/dp_{dat$data_shortname}-{pipeline_id}.R")
}
